#!/bin/sh

sh $WORKING_DIR/test.sh

sh $WORKING_DIR/test2.sh foo bar

##file test.sh --scala <<EOF_FILE
    //##wrap Main
    println("Hello");
EOF_FILE

##file test2.sh --scala <<EOF_FILE
    //##wrap Main
    //##-c scala Main "World!" "$@"
    println("Hello " + args.mkString(" "));
EOF_FILE
