#!/bin/sh

TITLE=
while [ "$#" != 0 ]; do
    if [ $1 = '--title' ]; then
        TITLE=$2
        shift
    fi
    shift
done

cat <<EOF
<html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
EOF

perl -F'\t' -nae '
  print "          [";
  if ($. > 1) {
    my $x = shift(@F);
    if ($x =~ /\A[0-9]+\z/ || $x =~ /\A[0-9]+\.[0-9]*\z/) {
      print "$a, ";
    } elsif ($x =~ /\A([0-9]+)\/([0-9]+)\/([0-9]+)\z/) {
      my $m = $2 - 1;
      print "new Date($1, $m, $3), ";
    } else {
      print "\"$a\", ";
    }
    foreach my $a (@F) {
      $a =~ s/\A\s*(.*)\s*\z/$1/g;
      print "$a, ";
    }
  } else {
    foreach my $a (@F) {
      $a =~ s/\A\s*(.*)\s*\z/$1/g;
      print "\"$a\", ";
    }
  }
  print "],\n";
'

cat <<EOF
        ]);

        var options = {
          title: '$TITLE'
        };

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
      }
    </script>
  </head>
  <body>
    <div id="chart_div" style="width: 900px; height: 500px;"></div>
  </body>
</html>

