#!/bin/sh

perl -0777 -ne '
    if (/\A\s*[_.\[\]\"0-9A-Za-z]+\((.+)\);?\s*\Z/) {
        print $1;
    } elsif (/\A\s*[^=]+\s*=\s*\((.+)\);?\s*\Z/) {
        print $1;
    } else {
        print $_;
    }
'

