#!/usr/bin/env php
<?php

function print_data($head, $data) {
    if (is_array($data)) {
        if (is_list($data)) {
            echo "$head\tlist\t\n";
            $count = count($data);
            for ($ii = 0; $ii < $count; $ii++) {
                print_data ("$head/$ii", $data[$ii]);
            }
        } else {
            echo "$head\tmap\t\n";
            foreach ($data as $key => $value) {
                $key = str_replace("%", "%25", $key);
                $key = str_replace("/", "%2F", $key);
                $key = str_replace(" ", "%20", $key);
                $key = str_replace("\t", "%09", $key);
                print_data ("$head/$key", $value);
            }
        }
    } else if (is_int($data)) {
        echo "$head\tint\t$data\n";;
    } else if (is_float($data)) {
        echo "$head\tfloat\t$data\n";;
    } else if (is_bool($data)) {
        if ($data) {
            echo "$head\tbool\ttrue\n";;
        } else {
            echo "$head\tbool\tfalse\n";;
        }
    } else {
        $data = explode("\n", $data);
        $is_first = true;
        foreach ($data as $l) {
            if ($is_first) {
                echo "$head\tstring\t$l\n";
                $is_first = false;
            } else {
                echo "$head\tappend\t$l\n";
            }
        }
    }
}

function is_list($data) {
    $count = count($data);
    for ($ii = 0; $ii < $count; $ii++) {
         if (!isset($data[$ii])) {
             return false;
         }
    }
    return true;
}

$stdin = file_get_contents('php://stdin');

// JSONPの場合は関数呼び出しを削除してJSONに修正
if (preg_match('/\A\s*[_.\[\]\"0-9A-Za-z]+\((.+)\);?\s*\Z/', $stdin, $matches)) {
    $stdin = $matches[1];
}

$data = json_decode($stdin, true);

print_data("", $data);

