#!/bin/sh
exec ttr "$0" -- "$@"

##working-dir --perm 103d77877cd44a5035ce008feeebd742

if [ ! -e $PERM_WORKING_DIR/sbt-launch.jar ]; then
    (
        cd $PERM_WORKING_DIR
        wget "http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.5/sbt-launch.jar" >&2
    ) || exit 1
fi

java -Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -jar $PERM_WORKING_DIR/sbt-launch.jar "$@"


