#!/bin/sh

sh $WORKING_DIR/main.sh

##file main.sh --scala <<EOF
//##wrap Main

val s = (1 until 8).foldLeft((math.random * 128).asInstanceOf[Long])((a, i) => a * 256 + (math.random * 256).asInstanceOf[Long]);

print("@SerialVersionUID(");
print(s);
print("L");
print(")\n");

EOF

